title: RubyInstaller for Windows - 国内镜像
email: ccmywish@qq.com
description: >
  Windows上安装Ruby的最简单方式

  完整独立的Windows安装包，包含Ruby解释器、MSYS2、文档等，无需安装WSL等虚拟机。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rubyinstaller.cn" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CONTRIBUTING.md
  - CHANGELOG.md
  - CNAME
  - Rakefile
  - LICENSE

# Ref: https://jekyllrb.com/docs/configuration/options/
# dotfiles are excluded by default
#  - .ruby-version

collections:
  "add-ons":
    output: true
  "about":
    output: true

feed:
  posts_limit: 20

issues_link: https://gitee.com/RubyKids/RubyInstaller.cn/issues
