title: RubyInstaller for Windows
email: 
description: > 
  Windows上安装Ruby的最简单方式

  这是一个独立的基于Windows的安装程序，包括Ruby语言、执行环境、重要文档等。
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - LICENSE.txt
  - add_checksums.rb

collections:
  "add-ons":
    output: true
  "about":
    output: true
