title: RubyInstaller for Windows - 国内镜像
email: 
description: > 
  Windows上安装Ruby的最简单方式

  完整独立的Windows安装包，包含Ruby解释器、MSYS2、文档等，无需安装WSL等虚拟机。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rubyinstaller.cn" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CONTRIBUTING.md
  - CNAME
  - Rakefile
  - LICENSE

collections:
  "add-ons":
    output: true
  "about":
    output: true
